MODULE_big = pg_ozerki
OBJS = anyarray_elemtype.o $(WIN32RES) schema_dump.o ozerki_utils.o ddl.o ddl_query.o

EXTENSION = pg_ozerki
DATA = pg_ozerki--1.0.sql

subdir = contrib/pg_ozerki
top_builddir = ../..
include $(top_builddir)/src/Makefile.global
include $(top_srcdir)/contrib/contrib-global.mk
